[package]
name = "templ-icons"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
convert_case = "0.9.0"
reqwest = { version = "0.12.24", features = ["blocking"] }
